### ISSUE TITLE
Can't seem to install correctly- cannot import name 'CuImage' from 'cucim'

### ISSUE THREAD

**Issue by choosehappy** [rapidsai/cucim#518]
**Describe the bug**
I followed the installation instructions and can't seem to get this to install correctly 

I also spun up a docker instance in WSL2 and that didn't appear to work either

**Steps/Code to reproduce bug**
Base-os
```
docker run -it -v `pwd`:/data --gpus all -p8888:8888 ubuntu bash
```

within docker:
```
apt update
apt install python3 python3-pip
pip install cucim
nvidia-smi # to check cuda version
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.70       Driver Version: 517.13       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   56C    P0    29W /  N/A |      0MiB / 16384MiB |      0%      Default |

pip install scipy scikit-image cupy-cuda117

python3 -c 'from cucim import CuImage'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'CuImage' from 'cucim' (/usr/local/lib/python3.10/dist-packages/cucim/__init__.py)


I feel like I'm missing something....what is it? : )  Thank you!

**Comment by choosehappy** [comment]
Quick update, this appears to happen in both python 3.10 (docker) and python 3.8 (WSL2 base)

```
----:/mnt/c/data/$ python3 --version
Python 3.8.10
----:/mnt/c/data/$ python3 -c 'from cucim import CuImage'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'CuImage' from 'cucim' (/home/ajanowc/.local/lib/python3.8/site-packages/cucim/__init__.py)

----:/mnt/c/data$ pip freeze | grep cuc
cucim==22.12.0
----:/mnt/c/data$ pip freeze | grep cup
cupy-cuda117==10.6.0
```

**Comment by grlee77** [comment]
Hi @choosehappy, sorry that this issue was overlooked. I think the problem was that Python 3.10 was not supported in cucim 22.12. If you either update to cucim >= 23.02 or downgrade to Python 3.9, I think it should work.

**Comment by grlee77** [comment]
please reopen if the suggestion in the prior comment does not resolve your issue
