### ISSUE TITLE
[BUG] No module named 'cucim.clara._cucim'

### ISSUE THREAD

**Issue by KumoLiu** [rapidsai/cucim#730]
cucim-cu12==2.4.0 works well in python 3.10, but not with 3.9
```
======================================================================
ERROR: test_wsi_sliding_window_splitter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_wsi_sliding_window_splitter
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/MONAI/MONAI/tests/test_wsi_sliding_window_splitter.py", line 26, in <module>
    has_cucim = has_cucim and hasattr(cucim, "CuImage")
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/lazy_loader/__init__.py", line 82, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/cucim/clara/__init__.py", line 21, in <module>
    from ._cucim import CuImage, DLDataType, DLDataTypeCode, cache, filesystem, io
ModuleNotFoundError: No module named 'cucim.clara._cucim'
```

related job
python3.10: https://github.com/Project-MONAI/MONAI/actions/runs/8658364208/job/23742102164#step:7:24659
python 3.9: https://github.com/Project-MONAI/MONAI/actions/runs/8658364208/job/23742102008#step:7:32219

**Comment by gigony** [comment]
Thanks, @KumoLiu, for the feedback!

It appears that the wheel files have not been properly updated to the PyPI registry: https://pypi.org/project/cucim-cu12/24.4.0/#files

The team is addressing this issue. Thank you!

**Comment by jakirkham** [comment]
Ok the wheels should now be up

@KumoLiu could you please retest?

**Comment by KumoLiu** [comment]
Hi @gigony and @jakirkham, thanks for the quick fix.
I retested, works well now.
https://github.com/Project-MONAI/MONAI/actions/runs/8810156566/job/24182078367?pr=7696#step:7:16093

**Comment by jakirkham** [comment]
Glad to hear it. Thanks @KumoLiu ! 🙏

Let's close this out as resolved then
