### ISSUE TITLE
[BUG]  RuntimeError: Didn't find wheel for cucim-cu12 24.10.0

### ISSUE THREAD

**Issue by jazberna1** [rapidsai/cucim#794]
**Describe the bug**
Hi!
I am trying to install cucim by typing:
```
pip install cucim-cu12
```

when donig so I get the error:
```
RuntimeError: Didn't find wheel for cucim-cu12 24.10.0
```

I have included the full message at the end.

**Steps/Code to reproduce bug**

In my case I am installing cucim in a conda environment (python=3.11) and then typing:
```
pip install cucim-cu12
```

**Expected behavior**
Get cucim installed

**Environment details (please complete the following information):**
 I am installing cucim in a conda environment (python=3.11)
 Python Version: CPython 3.11.10
 Operating System: Windows 10
 CPU Architecture: AMD64
 Driver Version: 537.42
 CUDA Version: 12.2

**Additional context**
This is the full message, error included, after running` pip install cucim-cu12` :
```
Collecting cucim-cu12
  Using cached cucim_cu12-24.10.0.tar.gz (3.2 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      INFO:nvidia-stub:Testing wheel cucim_cu12-24.10.0-cp310-cp310-manylinux_2_28_aarch64.whl against tag cp310-cp310-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cucim_cu12-24.10.0-cp310-cp310-manylinux_2_28_x86_64.whl against tag cp310-cp310-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cucim_cu12-24.10.0-cp311-cp311-manylinux_2_28_aarch64.whl against tag cp311-cp311-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cucim_cu12-24.10.0-cp311-cp311-manylinux_2_28_x86_64.whl against tag cp311-cp311-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cucim_cu12-24.10.0-cp312-cp312-manylinux_2_28_aarch64.whl against tag cp312-cp312-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cucim_cu12-24.10.0-cp312-cp312-manylinux_2_28_x86_64.whl against tag cp312-cp312-manylinux_2_28_x86_64
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hh1cd7jt\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 177, in download_wheel
          return download_manual(wheel_directory, distribution, version)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hh1cd7jt\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 144, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      Traceback (most recent call last):
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hh1cd7jt\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 177, in download_wheel
          return download_manual(wheel_directory, distribution, version)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hh1cd7jt\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 144, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      RuntimeError: Didn't find wheel for cucim-cu12 24.10.0

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\malieva\miniconda3\envs\ultrack\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\xxx\miniconda3\envs\ultrack\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\miniconda3\envs\ultrack\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hh1cd7jt\overlay\Lib\site-packages\nvidia_stub\buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hh1cd7jt\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 179, in download_wheel
          report_install_failure(distribution, version, exception_context)
        File "C:\Users\xxx\AppData\Local\Temp\pip-build-env-hh1cd7jt\overlay\Lib\site-packages\nvidia_stub\error.py", line 63, in report_install_failure
          raise InstallFailedError(
      nvidia_stub.error.InstallFailedError:
      *******************************************************************************

      The installation of cucim-cu12 for version 24.10.0 failed.

      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com. If https://pypi.nvidia.com is not reachable, we
      cannot download the real wheel file to install.

      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com cucim-cu12
      ```

      Here is some debug information about your platform to include in any bug
      report:

      Python Version: CPython 3.11.10
      Operating System: Windows 10
      CPU Architecture: AMD64
      Driver Version: 537.42
      CUDA Version: 12.2

      *******************************************************************************

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Thanks so much!! Any help will be much appreciated.
Jorge

**Comment by jakirkham** [comment]
That is because this is hosted on a different index. So one needs to add the index URL as well (like below)

```
python -m pip install --extra-index-url=https://pypi.nvidia.com cucim-cu12
```

**Comment by gigony** [comment]
Hi @jazberna1 ,
It looks like you're trying to install cuCIM on Windows.
Please refer to the following link to install only the image processing components of cuCIM (scikit-image API) on Windows. IO part is not available on Windows:
- https://github.com/rapidsai/cucim/issues/454#issuecomment-1331244039

```sh
pip install -e "git+https://github.com/rapidsai/cucim.git@v24.10.00#egg=cucim-cu12&subdirectory=python/cucim" scipy scikit-image
```

**Comment by jazberna1** [comment]
Hi!

Thanks so much!! I followed the link above and installed cucim on windows with this command:

`pip install -e "git+https://github.com/rapidsai/cucim.git@v22.04.00#egg=cucim&subdirectory=python/cucim" scipy scikit-image`

Thanks!
Jorge
